// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    NutDatePicker: typeof import('@nutui/nutui-taro')['DatePicker']
    NutInput: typeof import('@nutui/nutui-taro')['Input']
    NutPopup: typeof import('@nutui/nutui-taro')['Popup']
  }
}
